#!/usr/bin/env bash
#sudo add-apt-repository ppa:ethereum/ethereum
#sudo apt update
#sudo apt install solc

pip3 install web3
pip3 install py-solc
pip3 install PyJWT

export PYTHONPATH=$PYTHONPATH:$PWD
echo $PYTHONPATH
testrpc &
sleep 1s
echo
echo
echo -ne 'Wait 3 sec for deployment\r'
sleep 1s
echo -ne 'Wait 2 sec for deployment\r'
sleep 1s
echo -ne 'Wait 1 sec for deployment\r'
sleep 1s
echo 'Starting deployment'
python3 deploy.py
